# Question 1
Consider the following Python module:
a = 0
def b():
 global a
 a = c(a)
def c(a):
 return a + 2
After importing the module into the interpreter, you execute:
>>> b()
>>> b()
>>> b()
>>> a
?
What value is displayed when the last expression (a) is evaluated? Explain your
answer by indicating what happens in every executed statement.

In [41]:
a = 0
def b():
    global a
    a = c(a)

def c(a):
    return a + 2

b() #first function call
b() #second function call
b() #third function call

print(a)

6

# Explaination for Question 1:
In the first function call:

where a = 0. 
we call c(a) with a=0.
now c(0) returns 0 + 2 = 2 meaning now a = 2.

In the second function call:

where a = 2.
c(a) is called with a=2.
c(2) returns 2 + 2 = 4 meaning now a = 4.

In the third function call:
where a = 4.
c(a) is called with a=4.
c(4) returns 4 + 2 = 6 meaning now a = 6.

### Hence, after executing b() three times, the final value of a will be 6.

# Question 2
Function fileLength(), given to you, takes the name of a file as input and returns
the length of the file:
>>> fileLength('midterm.py')
284
>>> fileLength('idterm.py')
Traceback (most recent call last):
File "<pyshell#34>", line 1, in <module>
 fileLength('idterm.py')
File "/Users/me/midterm.py", line 3, in fileLength
 infile = open(filename)
FileNotFoundError: [Errno 2] No such file or directory:
'idterm.py'
As shown above, if the file cannot be found by the interpreter or if it cannot be read
as a text file, an exception will be raised. Modify function fileLength() so that a
friendly message is printed instead:
>>> fileLength('midterm.py')
358
>>> fileLength('idterm.py')
File idterm.py not found.

In [42]:
def fileLength(filename):
    try:
        with open(filename, 'r') as infile:
            content = infile.read()
        return len(content)
    except FileNotFoundError:
        print(f"File {filename} not found.")

print(fileLength('Filelength.txt')) 
print(fileLength('idterm.py'))    # This should display the friendly error message

123
File idterm.py not found.
None

# Question 3
Write a class named Marsupial that can be used as shown below:
>>> m = Marsupial()
>>> m.put_in_pouch('doll')
>>> m.put_in_pouch('firetruck')
>>> m.put_in_pouch('kitten')
>>> m.pouch_contents()
['doll', 'firetruck', 'kitten']
Now write a class named Kangaroo as a subclass of Marsupial that inherits all the
attributes of Marsupial and also:
a. extends the Marsupial __init__ constructor to take, as input, the
coordinates x and y of the Kangaroo object,
b. supports method jump that takes number values dx and dy as input and
moves the kangaroo by dx units along the x-axis and by dy units along the yaxis, and
c. overloads the __str__ operator so it behaves as shown below.
>>> k = Kangaroo(0,0)
>>> print(k)
I am a Kangaroo located at coordinates (0,0)
>>> k.put_in_pouch('doll')
>>> k.put_in_pouch('firetruck')
>>> k.put_in_pouch('kitten')
>>> k.pouch_contents()
['doll', 'firetruck', 'kitten']
>>> k.jump(1,0)
>>> k.jump(1,0)
>>> k.jump(1,0)
>>> print(k)
I am a Kangaroo located at coordinates (3,0)

In [43]:
class Marsupial:
    def __init__(self):
        # Initialize an empty list for the pouch
        self.pouch = []

    def put_in_pouch(self, item):
        # Add an item to the pouch list
        self.pouch.append(item)

    def pouch_contents(self):
        # Return the contents of the pouch
        return self.pouch

class Kangaroo(Marsupial):
    def __init__(self, x, y):
        # Call the superclass constructor to initialize the pouch
        super().__init__()
        # Initialize coordinates
        self.x = x
        self.y = y

    def jump(self, dx, dy):
        # Move the kangaroo by dx and dy units
        self.x += dx
        self.y += dy

    def __str__(self):
        # Override the string representation to show coordinates
        return f"I am a Kangaroo located at coordinates ({self.x},{self.y})"

# Creating a Marsupial object
m = Marsupial()
m.put_in_pouch('doll')
m.put_in_pouch('firetruck')
m.put_in_pouch('kitten')
print(m.pouch_contents())  # Expected output: ['doll', 'firetruck', 'kitten']

# Creating a Kangaroo object
k = Kangaroo(0, 0)
print(k)  # Expected output: I am a Kangaroo located at coordinates (0,0)
k.put_in_pouch('doll')
k.put_in_pouch('firetruck')
k.put_in_pouch('kitten')
print(k.pouch_contents())  # Expected output: ['doll', 'firetruck', 'kitten']
k.jump(1, 0)
k.jump(1, 0)
k.jump(1, 0)
print(k)  # Expected output: I am a Kangaroo located at coordinates (3,0)

['doll', 'firetruck', 'kitten']
I am a Kangaroo located at coordinates (0,0)
['doll', 'firetruck', 'kitten']
I am a Kangaroo located at coordinates (3,0)

# Question 4
Write function collatz() that takes a positive integer x as input and prints the
Collatz sequence starting at x. A Collatz sequence is obtained by repeatedly applying
this rule to the previous number x in the sequence:
x = {
𝑥/2 𝑖𝑓 𝑥 𝑖𝑠 𝑒𝑣𝑒𝑛
3𝑥 + 1 𝑖𝑓 𝑥 𝑖𝑠 𝑜𝑑𝑑
Your function should stop when the sequence gets to number 1. Your
implementation must be recursive, without any loops.
>>> collatz(1)
1
>>> collatz(10)
10
5
16
8
4
2
1

In [44]:
def collatz(x):
    # Print the current number in the sequence
    print(x)
    # Base case: stop recursion if x is 1
    if x == 1:
        return
    # Recursive case: apply the Collatz rule
    elif x % 2 == 0:
        collatz(x // 2)  # x is even
    else:
        collatz(3 * x + 1)  # x is odd
        
collatz(1)
collatz(10)

1
10
5
16
8
4
2
1

# Question 5
Write a recursive method binary() that takes a non-negative
integer n and prints the binary representation of integer n.
>>> binary(0)
0
>>> binary(1)
1
>>> binary(3)
11
>>> binary(9)
1001

In [45]:
def binary(n):
    # Base case: if n is 0 or 1, print n directly
    if n < 2:
        print(n, end='')  # end='' keeps the output on the same line
    else:
        # Recursive case: divide n by 2 and call binary() with the quotient
        binary(n // 2)
        # Print the remainder (either 0 or 1) after recursive call
        print(n % 2, end='')  # end='' keeps the output on the same line

binary(0)
print()
binary(1)
print()
binary(3)
print()
binary(9)
print()

0
1
11
1001

# Question 6
Implement a class named HeadingParser that can be used to parse an HTML
document, and retrieve and print all the headings in the document. You should
implement your class as a subclass of HTMLParser, defined in Standard Library
module html.parser. When fed a string containing HTML code, your class should
print the headings, one per line and in the order in which they appear in the
document. Each heading should be indented as follows: an h1 heading should have
indentation 0, and h2 heading should have indentation 1, etc. Test your
implementation using w3c.html.
>>> infile = open('w3c.html')
>>> content = infile.read()
>>> infile.close()
>>> hp = HeadingParser()
>>> hp.feed(content)
W3C Mission
Principles

In [47]:
from html.parser import HTMLParser

class HeadingParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.indentation = 0
        self.headings = []

    def handle_starttag(self, tag, attrs):
        if tag.startswith('h') and len(tag) > 1 and tag[1].isdigit():
            self.indentation = int(tag[1]) - 1

    def handle_data(self, data):
        if data.strip() != '':
            self.headings.append((' ' * self.indentation) + data.strip())

    def print_headings(self):
        for heading in self.headings:
            print(heading)


with open('w3c.html', 'r') as f:
    content = f.read()

hp = HeadingParser()
hp.feed(content)
hp.print_headings()

@page { size: 8.27in 11.69in; margin: 0.79in }
		p { line-height: 115%; margin-bottom: 0.1in; background: transparent }
		pre { background: transparent }
		pre.western { font-family: "Liberation Mono", monospace; font-size: 10pt }
		pre.cjk { font-family: "NSimSun", monospace; font-size: 10pt }
		pre.ctl { font-family: "Liberation Mono", monospace; font-size: 10pt }
<!DOCTYPE html>
<html lang="en">

<head>
  <meta name="description" content="Webpage description goes here" />
  <meta charset="utf-8">
  <title>Change_me</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="">
  <link rel="stylesheet" href="css/style.css">
</head>

<body>

	<h1>W3C Mission</h1>
	<h2>Principles</h2>



</body>
</html>

# Question 7
Implement recursive function webdir() that takes as input: a URL (as a string) and
non-negative integers depth and indent. Your function should visit every web
page reachable from the starting URL web page in depth clicks or less, and print
each web page's URL. As shown below, indentation, specified by indent, should
be used to indicate the depth of a URL.
>>>
webdir('http://reed.cs.depaul.edu/lperkovic/csc242/test1.html'
, 2, 0)
http://reed.cs.depaul.edu/lperkovic/csc242/test1.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test2.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test4.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test3.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test4.html

In [57]:
import requests
from bs4 import BeautifulSoup

def webdir(url, depth, indent):
    # Print the current URL
    print(' ' * indent + url)
    
    if depth == 0:
        return

    try:
        # Fetch page content
        response = requests.get(url)
        response.raise_for_status()  # This will raise an error for 4xx/5xx responses
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Find all the links of page
        for link in soup.find_all('a', href=True):
            # Get the absolute URL
            href = link.get('href')
            absolute_url = requests.compat.urljoin(url, href)
            
            # Recursively visit each link, with increased indent and decreased depth
            webdir(absolute_url, depth - 1, indent + 1)

    except requests.exceptions.RequestException as e:
        print(f"Could not retrieve or parse the page: {url}, error: {e}")

# Since given url was giving 404 error i have used example.com for testing purposes
webdir('https://www.example.com', 2, 0)

https://www.example.com
 https://www.iana.org/domains/example
  https://www.iana.org/
  https://www.iana.org/domains
  https://www.iana.org/protocols
  https://www.iana.org/numbers
  https://www.iana.org/about
  https://www.iana.org/go/rfc2606
  https://www.iana.org/go/rfc6761
  https://www.iana.org/domains/reserved
  https://www.iana.org/domains
  https://www.iana.org/domains/root
  https://www.iana.org/domains/int
  https://www.iana.org/domains/arpa
  https://www.iana.org/domains/idn-tables
  https://www.iana.org/numbers
  https://www.iana.org/abuse
  https://www.iana.org/protocols
  https://www.iana.org/protocols
  https://www.iana.org/time-zones
  https://www.iana.org/about
  https://www.iana.org/performance
  https://www.iana.org/reports
  https://www.iana.org/reviews
  https://www.iana.org/about/excellence
  https://www.iana.org/contact
  http://pti.icann.org
  http://www.icann.org/
  https://www.icann.org/privacy/policy
  https://www.icann.org/privacy/tos

# Question 8
Write SQL queries on the below database table that return:
a) All the temperature data.
b) All the cities, but without repetition.
c) All the records for India.
d) All the Fall records.
e) The city, country, and season for which the average rainfall is between 200
and 400 millimeters.
f) The city and country for which the average Fall temperature is above 20
degrees, in increasing temperature order.
g) The total annual rainfall for Cairo.
h) The total rainfall for each season.

In [52]:
import sqlite3

conn = sqlite3.connect('my_db.db')
cur = conn.cursor()
cur.execute("DROP TABLE IF EXISTS WeatherData")

cur.execute('''CREATE TABLE WeatherData (
                City TEXT,
                Country TEXT,
                Season TEXT,
                Temperature REAL,
                Rainfall REAL)''')

cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Mumbai', 'India', 'Winter', 24.8, 5.9))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Mumbai', 'India', 'Spring', 28.4, 16.2))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Mumbai', 'India', 'Summer', 27.9, 1549.4))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Mumbai', 'India', 'Fall', 27.6, 346.0))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('London', 'United Kingdom', 'Winter', 4.2, 207.7))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('London', 'United Kingdom', 'Spring', 8.3, 169.6))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('London', 'United Kingdom', 'Summer', 15.7, 157.0))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('London', 'United Kingdom', 'Fall', 10.4, 218.5))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Cairo', 'Egypt', 'Winter', 13.6, 16.5))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Cairo', 'Egypt', 'Spring', 20.7, 6.5))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Cairo', 'Egypt', 'Summer', 27.7, 0.1))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Cairo', 'Egypt', 'Fall', 22.2, 4.5))
conn.commit()

# Close the connection
conn.close()

In [53]:
import sqlite3

conn = sqlite3.connect('my_db.db')
cur = conn.cursor()

cur.execute("SELECT Temperature FROM WeatherData")
print("All temperature data:")
print(cur.fetchall())

cur.execute("SELECT DISTINCT City FROM WeatherData")
print("\nAll cities:")
print(cur.fetchall())

cur.execute("SELECT * FROM WeatherData WHERE Country = 'India'")
print("\nAll records for India:")
print(cur.fetchall())

cur.execute("SELECT * FROM WeatherData WHERE Season = 'Fall'")
print("\nAll Fall records:")
print(cur.fetchall())

cur.execute("SELECT City, Country, Season FROM WeatherData WHERE Rainfall BETWEEN 200 AND 400")
print("\nCity, country, and season with average rainfall between 200 and 400 millimeters:")
print(cur.fetchall())

cur.execute("SELECT City, Country FROM WeatherData WHERE Season = 'Fall' AND Temperature > 20 ORDER BY Temperature ASC")
print("\nCity and country with average Fall temperature above 20 degrees:")
print(cur.fetchall())

cur.execute("SELECT SUM(Rainfall) FROM WeatherData WHERE City = 'Cairo'")
print("\nTotal annual rainfall for Cairo:")
print(cur.fetchone()[0])

cur.execute("SELECT Season, SUM(Rainfall) FROM WeatherData GROUP BY Season")
print("\nTotal rainfall for each season:")
print(cur.fetchall())

conn.close()

All temperature data:
[(24.8,), (28.4,), (27.9,), (27.6,), (4.2,), (8.3,), (15.7,), (10.4,), (13.6,), (20.7,), (27.7,), (22.2,)]

All cities:
[('Mumbai',), ('London',), ('Cairo',)]

All records for India:
[('Mumbai', 'India', 'Winter', 24.8, 5.9), ('Mumbai', 'India', 'Spring', 28.4, 16.2), ('Mumbai', 'India', 'Summer', 27.9, 1549.4), ('Mumbai', 'India', 'Fall', 27.6, 346.0)]

All Fall records:
[('Mumbai', 'India', 'Fall', 27.6, 346.0), ('London', 'United Kingdom', 'Fall', 10.4, 218.5), ('Cairo', 'Egypt', 'Fall', 22.2, 4.5)]

City, country, and season with average rainfall between 200 and 400 millimeters:
[('Mumbai', 'India', 'Fall'), ('London', 'United Kingdom', 'Winter'), ('London', 'United Kingdom', 'Fall')]

City and country with average Fall temperature above 20 degrees:
[('Cairo', 'Egypt'), ('Mumbai', 'India')]

Total annual rainfall for Cairo:
27.6

Total rainfall for each season:
[('Fall', 569.0), ('Spring', 192.29999999999998), ('Summer', 1706.5), ('Winter', 230.1)]

# Question 9
. Suppose list words is defined as follows:
>>> words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over',
'the', 'lazy', 'dog']
Write list comprehension expressions that use list words and generate the following
lists:
a) ['THE', 'QUICK', 'BROWN', 'FOX', 'JUMPS', 'OVER', 'THE',
'LAZY', 'DOG']
b) ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the',
'lazy', 'dog']
c) [3, 5, 5, 3, 5, 4, 3, 4, 3] (the list of lengths of words in list
words).
d) [['THE', 'the', 3], ['QUICK', 'quick', 5], ['BROWN',
'brown', 5], ['FOX', 'fox', 3], ['JUMPS', 'jumps', 5],
['OVER', 'over', 4], ['THE', 'the', 3], ['LAZY', 'lazy',
4], ['DOG', 'dog', 3]] (the list containing a list for every word of list
words, where each list contains the word in uppercase and lowercase and the
length of the word.)
e) ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the',
'lazy', 'dog'] (the list of words in list words containing 4 or more
characters.)

In [54]:
words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

uppercase_words = [word.upper() for word in words] # a) Convert all words to uppercase
print("a)", uppercase_words)

lowercase_words = [word.lower() for word in words] # b) Convert all words to lowercase
print("b)", lowercase_words)

word_lengths = [len(word) for word in words] # c) the list of lengths of words in list words
print("c)", word_lengths)

# d) List containing each word in uppercase, lowercase, and its length
detailed_words = [[word.upper(), word.lower(), len(word)] for word in words]
print("d)", detailed_words)

# e) List of words containing 4 or more characters
words_with_four_or_more = [word for word in words if len(word) >= 4]
print("e)", words_with_four_or_more)

a) ['THE', 'QUICK', 'BROWN', 'FOX', 'JUMPS', 'OVER', 'THE', 'LAZY', 'DOG']
b) ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
c) [3, 5, 5, 3, 5, 4, 3, 4, 3]
d) [['THE', 'the', 3], ['QUICK', 'quick', 5], ['BROWN', 'brown', 5], ['FOX', 'fox', 3], ['JUMPS', 'jumps', 5], ['OVER', 'over', 4], ['THE', 'the', 3], ['LAZY', 'lazy', 4], ['DOG', 'dog', 3]]
e) ['quick', 'brown', 'jumps', 'over', 'lazy']